from typing import Any

import schemathesis


def _find_entries(body: dict[str, Any]) -> list[dict[str, Any]]:
    if "entry" in body and isinstance(body["entry"], list):
        return body["entry"]
    return []


def _find_compositions(entries: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [
        item["resource"]
        for item in entries
        if item.get("resource") is not None
        and isinstance(item["resource"], dict)
        and item["resource"].get("resourceType") == "Composition"
    ]


@schemathesis.hook("before_call")
def ensure_composition_in_body(
    _ctx: schemathesis.HookContext, case: schemathesis.Case, *_kwargs: Any
) -> schemathesis.Case:
    """
    Hook to ensure that when schemathesis generates a request body,
    it always contains a Composition resource.
    """
    if isinstance(case.body, dict):
        entries = _find_entries(case.body)
        if len(_find_compositions(entries)) == 0:
            # If no Composition resource is found, add a valid entry to satisfy
            # the schema
            entries.append(
                {
                    "fullUrl": "composition",
                    "resource": {
                        "resourceType": "Composition",
                        "subject": {
                            "identifier": {
                                "system": "https://fhir.nhs.uk/Id/nhs-number",
                                "value": "nhs_number",
                            }
                        },
                    },
                }
            )
            case.body["entry"] = entries
    return case


@schemathesis.hook("filter_body")
def ignore_multiple_composition_requests(
    _: schemathesis.HookContext, body: dict[str, Any]
) -> bool:
    """
    Hook to filter out any requests generated by schemathesis that contain more
    than one Composition resource.
    """
    composition_resources = _find_compositions(_find_entries(body))
    return len(composition_resources) < 2
