name: "Setup Python project"
description: "Setup Python, install Poetry, and install project dependencies"
inputs:
  python-version:
    description: "Python version to install"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: "Install Poetry"
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: "Install dependencies"
      shell: bash
      run: make dependencies
