name: "Deploy Proxy"
description: "Deploy proxy to API management platform"
runs:
  using: "composite"
  steps:
    - name: "Deploy Proxy"
      working-directory: "pathology-api"
      shell: bash
      run: |
        echo "Current directory: $(pwd)"
        echo "Looking for openapi.yaml..."
        ls -la openapi.yaml
        echo "Deploying proxy..."
        proxygen instance deploy internal-dev "pathology-laboratory-reporting-${{ inputs.pr-number }}" openapi.yaml --no-confirm
