name: Tear Down API Proxy
description: Delete the API proxy instance using Proxygen

inputs:
  proxy-base-path:
    description: 'A unique base path for the proxy instance'
    required: true
  proxygen-key-secret:
    description: 'Proxygen private key secret'
    required: true

runs:
  using: composite
  steps:
    - name: Configure Proxygen
      uses: ./.github/actions/configure-proxygen
      with:
        proxygen-key-secret: ${{ inputs.proxygen-key-secret }}

    - name: Tear down preview API proxy
      shell: bash
      run: |
        proxygen instance delete internal-dev {{ inputs.proxy-base-path }} --no-confirm
