name: Configure Proxygen
description: Install yq for yaml, install proxygen-cli and configure the account

inputs:
  proxygen-key-secret:
    description: 'Proxygen private key secret'
    required: true

runs:
  using: composite
  steps:
    - name: Install yq for YAML template processing
      shell: bash
      run: |
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq

    - name: Install Proxygen CLI
      shell: bash
      run: |
        pip install proxygen-cli
        proxygen --version

    - name: Configure proxygen account details
      shell: bash
      working-directory: proxygen
      run: |
        cp settings.yaml $HOME/.proxygen/settings.yaml

        printf "%s" "${{ inputs.proxygen-key-secret }}" > /tmp/proxygen_private_key.pem
        cp credentials.template.yaml $HOME/.proxygen/credentials.yaml
        yq eval '.private_key_path = "/tmp/proxygen_private_key.pem"' -i $HOME/.proxygen/credentials.yaml
