name: "Start local Lambda environment"
description: "Start a local AWS Lambda environment for testing"
inputs:
  deploy-command:
    description: "Command to start local Lambda"
    required: false
    default: "make deploy"
  health-path:
    description: "Health probe path to POST"
    required: false
    default: "/"
  max-seconds:
    description: "Maximum seconds to wait for readiness"
    required: false
    default: "60"
python-version:
    description: "Python version to install"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Start local Lambda environment"
      shell: bash
      env:
        PYTHON_VERSION: ${{ inputs.python-version }}
      run: |
        set -euo pipefail
        echo "Starting local Lambda: '${{ inputs.deploy-command }}'"
        bash -c "${{ inputs.deploy-command }}"
