name: "Start local Lambda environment"
description: "Start a local AWS Lambda environment for testing"
inputs:
  deploy-command:
    description: "Command to start local Lambda"
    required: false
    default: "make deploy"
  health-path:
    description: "Health probe path to POST"
    required: false
    default: "/"
  max-seconds:
    description: "Maximum seconds to wait for readiness"
    required: false
    default: "60"
python-version:
    description: "Python version to install"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Start local Lambda environment"
      shell: bash
      env:
        PYTHON_VERSION: ${{ inputs.python-version }}
      run: |
        set -euo pipefail
        echo "Starting local Lambda: '${{ inputs.deploy-command }}'"
        nohup ${{ inputs.deploy-command }} >/tmp/lambda.log 2>&1 &
        echo $! > /tmp/lambda.pid
        echo "PID: $(cat /tmp/lambda.pid)"
    - name: "Wait for Lambda to be ready"
      shell: bash
      run: |
        set -euo pipefail
        BASE_URL="${BASE_URL:-http://localhost:5001}"
        HEALTH_URL="${BASE_URL}${{ inputs.health-path }}"
        MAX="${{ inputs.max-seconds }}"
        echo "Waiting for Lambda at ${HEALTH_URL} (max ${MAX}s)..."
        for i in $(seq 1 "${MAX}"); do
          if curl -sSf -X POST "${HEALTH_URL}" -d '{}' >/dev/null; then
            echo "Lambda is ready"
            exit 0
          fi
          sleep 1
        done
        echo "Lambda did not become ready in time"
        echo "---- recent lambda log ----"
        tail -n 200 /tmp/lambda.log || true
        exit 1
