openapi: 3.0.3
info:
  title: Pathology and Laboratory Medicine Reporting - FHIR API
  description: Clinical Data Pathology API
  version: 0.1.0
  contact:
    name: API Support
servers:
  - url: http://localhost:5002
    description: Local development server
paths:
  /FHIR/R4/Bundle:
    post:
      security:
      - app-level3: []
      summary: Provide a new test result
      description: Provide a new test result to the pathology API
      operationId: postBundle
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              type: object
              required:
                - resourceType
                - type
                - entry
              properties:
                resourceType:
                  type: string
                  enum:
                    - Bundle
                  description: FHIR resource type
                meta:
                  $ref: "#/components/schemas/meta"
                type:
                  type: string
                  enum:
                    - document
                  description: The type of the bundle
                  example: document
                entry:
                  type: array
                  description: |
                    Entries that form a Test Result. Any included entries should comply with the [Pathology FHIR Implementation Guide|https://simplifier.net/guide/pathology-fhir-implementation-guide/Home?version=0.2.0], though the resources listed below are additionally required by the Pathology API:
                    | Resource Type | Required Fields |
                    |---------------|-----------------|
                    | Composition   | - `subject` - Required to identify the Patient a given Test Result is for. The Subject should include an `identifier` referencing the `https://fhir.nhs.uk/Id/nhs-number` System value. |
                  items:
                    type: object
                    required:
                      - fullUrl
                      - resource
                    properties:
                      fullUrl:
                        type: string
                        description: URI for resource
                        example: "composition"
                      resource:
                        anyOf:
                          - $ref: "#/components/schemas/CompositionResource"
                          - type: object
                            required:
                              - resourceType
                            properties:
                              resourceType:
                                type: string
                                description: Type of FHIR resource (e.g. "Patient", "Observation", etc.)
                                enum:
                                  - Patient
                                  - Observation
                                  - DiagnosticReport
                                  - Specimen
                                  - ServiceRequest
                                  - Practitioner
                                  - PractitionerRole
                                  - Organization
                                example: Patient
                              meta:
                                $ref: "#/components/schemas/meta"
      responses:
        '200':
          description: Successful response
          content:
            application/fhir+json:
              schema:
                type: object
                required:
                  - resourceType
                  - type
                properties:
                  resourceType:
                    type: string
                    enum:
                      - Bundle
                    description: FHIR resource type (always "Bundle")
                  meta:
                    type: object
                    description: Metadata about the resource
                    nullable: true
                  type:
                    type: string
                    enum:
                      - document
                      - transaction
                    description: The type of the bundle
                  identifier:
                    type: object
                    nullable: true
                    description: Persistent identifier for the bundle (UUID)
                    properties:
                      system:
                        type: string
                        format: uri
                      value:
                        type: string
                        format: uuid
                  entry:
                    type: array
                    nullable: true
                    description: Entries in the bundle
                    items:
                      type: object
                      required:
                        - fullUrl
                        - resource
                      properties:
                        fullUrl:
                          type: string
                          description: URI for resource
                        resource:
                          type: object
                          required:
                            - resourceType
        '400':
          description: Invalid request
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/OperationOutcome"
        '500':
          description: Unexpected internal error
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/OperationOutcome"

components:
  securitySchemes:
      app-level3:
        $ref: https://proxygen.ptl.api.platform.nhs.uk/components/securitySchemes/app-level3
  schemas:
    meta:
      type: object
      properties:
        profile:
          type: array
          items:
            type: string
        versionId:
          type: string
    CompositionResource:
      type: object
      required:
        - resourceType
        - subject
      properties:
        resourceType:
          type: string
          description: Type of FHIR resource (Always "Composition")
          enum:
            - Composition
          example: Composition
        meta:
          $ref: "#/components/schemas/meta"
        subject:
          type: object
          required:
            - identifier
          properties:
            identifier:
              type: object
              required:
                - system
                - value
              properties:
                system:
                  type: string
                  enum:
                    - "https://fhir.nhs.uk/Id/nhs-number"
                  example: "https://fhir.nhs.uk/Id/nhs-number"
                value:
                  type: string
                  example: "9999999999"
    OperationOutcome:
      type: object
      required:
        - resourceType
        - issue
      properties:
        resourceType:
          type: string
          enum:
            - OperationOutcome
          example: OperationOutcome
        issue:
          type: array
          items:
            type: object
            required:
              - severity
              - code
              - diagnostics
            properties:
              severity:
                type: string
                enum:
                  - fatal
                  - error
                example: error
              code:
                type: string
                enum:
                  - invalid
                  - not-found
                  - exception
                example: invalid
              diagnostics:
                type: string
